
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb1q\xce\x9e^\xd6\x1d\xfa\x04\x1e\xca\xf2\x7f1\x02\xb9'
    
_lr_action_items = {'embedded_python':([27,],[31,]),'check':([15,20,31,],[-10,27,-11,]),')':([9,10,11,14,21,22,24,25,28,29,32,33,],[15,-6,-8,-16,-7,-12,-9,-17,32,-13,-14,-15,]),'(':([5,17,23,30,],[7,23,23,23,]),'|':([12,13,14,22,24,25,26,28,29,32,33,],[-19,19,-16,-12,30,-17,-20,30,-13,-14,-15,]),'*':([14,22,24,25,28,29,32,33,],[-16,-12,29,-17,29,-13,-14,29,]),',':([9,10,11,14,21,22,24,25,29,32,33,],[16,-6,-8,-16,-7,-12,-9,-17,-13,-14,-15,]),'.':([12,14,22,25,26,],[18,-16,18,-17,18,]),'=':([5,11,],[8,17,]),'ID':([0,1,2,3,4,6,7,8,12,13,14,15,16,17,18,19,20,23,25,26,30,31,],[5,-1,-3,5,-4,-2,11,14,-19,-18,-16,-10,11,14,25,14,-5,14,-17,-20,14,-11,]),'$end':([1,2,3,4,6,12,13,14,15,20,25,26,31,],[-1,-3,0,-4,-2,-19,-18,-16,-10,-5,-17,-20,-11,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'class_name':([8,17,19,23,30,],[12,22,26,22,22,]),'fields_list':([7,],[9,]),'rule':([0,3,],[1,6,]),'field_rule':([0,3,],[2,2,]),'field':([7,16,],[10,21,]),'alternatives_list':([8,],[13,]),'tree_grammar':([0,],[3,]),'alternatives_rule':([0,3,],[4,4,]),'checks_list':([15,],[20,]),'expression':([17,23,30,],[24,28,33,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tree_grammar","S'",1,None,None,None),
  ('tree_grammar -> rule','tree_grammar',1,'p_tree_grammar','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',154),
  ('tree_grammar -> tree_grammar rule','tree_grammar',2,'p_tree_grammar','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',155),
  ('rule -> field_rule','rule',1,'p_rule','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',163),
  ('rule -> alternatives_rule','rule',1,'p_rule','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',164),
  ('field_rule -> ID ( fields_list ) checks_list','field_rule',5,'p_field_rule','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',168),
  ('fields_list -> field','fields_list',1,'p_fields_list','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',172),
  ('fields_list -> fields_list , field','fields_list',3,'p_fields_list','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',173),
  ('field -> ID','field',1,'p_field','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',181),
  ('field -> ID = expression','field',3,'p_field','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',182),
  ('checks_list -> <empty>','checks_list',0,'p_checks_list','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',189),
  ('checks_list -> checks_list check embedded_python','checks_list',3,'p_checks_list','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',190),
  ('expression -> class_name','expression',1,'p_expression','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',198),
  ('expression -> expression *','expression',2,'p_expression','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',199),
  ('expression -> ( expression )','expression',3,'p_expression','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',200),
  ('expression -> expression | expression','expression',3,'p_expression','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',201),
  ('class_name -> ID','class_name',1,'p_class_name','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',217),
  ('class_name -> class_name . ID','class_name',3,'p_class_name','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',218),
  ('alternatives_rule -> ID = alternatives_list','alternatives_rule',3,'p_alternatives_rule','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',225),
  ('alternatives_list -> class_name','alternatives_list',1,'p_alternatives_list','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',229),
  ('alternatives_list -> alternatives_list | class_name','alternatives_list',3,'p_alternatives_list','/usr/local/lib/python2.7/dist-packages/asp/tree_grammar.py',230),
]
